import express from "express";
import fetch from "node-fetch";
import { simpleGit } from "simple-git";
import dotenv from "dotenv";
import fs from "fs";
import path from "path";

dotenv.config();

const app = express();
app.use(express.json());

const CLAUDE_API_KEY = process.env.CLAUDE_API_KEY;
const GITEA_TOKEN = process.env.GITEA_TOKEN;
const GITEA_BASE_URL = process.env.GITEA_BASE_URL || "http://localhost:3000";
const SLACK_WEBHOOK_URL = process.env.SLACK_WEBHOOK_URL;

async function sendSlackAlert(message) {
  if (!SLACK_WEBHOOK_URL) return;
  await fetch(SLACK_WEBHOOK_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ text: message }),
  });
}

async function updateGiteaIssue(owner, repo, issueNumber, comment) {
  await fetch(`${GITEA_BASE_URL}/api/v1/repos/${owner}/${repo}/issues/${issueNumber}/comments`, {
    method: "POST",
    headers: {
      "Authorization": `token ${GITEA_TOKEN}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({ body: comment })
  });
}

async function createGiteaPR(owner, repo, base, head, title, body) {
  const response = await fetch(`${GITEA_BASE_URL}/api/v1/repos/${owner}/${repo}/pulls`, {
    method: "POST",
    headers: {
      "Authorization": `token ${GITEA_TOKEN}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({ base, head, title, body })
  });
  return await response.json();
}

app.post("/webhook", async (req, res) => {
  const event = req.headers["x-gitea-event"];
  console.log(`Received event: ${event}`);

  if (event === "issues") {
    const { action, issue, repository } = req.body;
    if (action !== "opened") return res.sendStatus(200);

    const owner = repository.owner.login;
    const repo = repository.name;
    const issueNumber = issue.number;

    await sendSlackAlert(`🚨 New Bug Reported: *${issue.title}* in ${repo}`);

    const prompt = `
    You are a senior engineer. Analyze this bug and respond ONLY with a JSON object.
    
    JSON Schema:
    {
      "severity": "low|medium|high|critical",
      "category": "frontend|backend|devops|security",
      "summary": "Brief analysis of the issue",
      "root_cause": "Hypothesis of the root cause",
      "suggested_fix": "Code snippet or logic to fix it",
      "patch_filename": "The file path that needs fixing (if applicable)",
      "patch_content": "The full content of the file with the fix applied (if applicable)"
    }

    Issue Title: ${issue.title}
    Issue Body: ${issue.body}
    `;

    try {
      const claudeResponse = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
          "x-api-key": CLAUDE_API_KEY,
          "anthropic-version": "2023-06-01",
          "content-type": "application/json"
        },
        body: JSON.stringify({
          model: "claude-3-5-sonnet-20240620",
          max_tokens: 1500,
          messages: [{ role: "user", content: prompt }]
        })
      });

      const data = await claudeResponse.json();
      const result = JSON.parse(data.content[0].text);

      const analysisComment = `🤖 **Claude Analysis:**\n\n- **Severity:** ${result.severity.toUpperCase()}\n- **Category:** ${result.category}\n- **Summary:** ${result.summary}\n- **Suggested Fix:**\n\`\`\`\n${result.suggested_fix}\n\`\`\``;
      
      await updateGiteaIssue(owner, repo, issueNumber, analysisComment);
      await sendSlackAlert(`🧠 Claude Triage: *${result.severity.toUpperCase()}* - ${result.summary}`);

      if (result.patch_content && result.patch_filename) {
        await handleAutoFix(owner, repo, issueNumber, result, repository.clone_url);
      }

    } catch (error) {
      console.error("Error processing Claude analysis:", error);
    }
  }

  res.sendStatus(200);
});

async function handleAutoFix(owner, repo, issueNumber, result, cloneUrl) {
  const tempDir = path.join(process.cwd(), "temp_repos", `issue-${issueNumber}-${Date.now()}`);
  const branchName = `fix/issue-${issueNumber}`;
  const git = simpleGit();

  try {
    console.log(`Cloning ${cloneUrl} into ${tempDir}...`);
    // Note: In production, use auth in cloneUrl or set git credentials
    await git.clone(cloneUrl, tempDir);
    
    const localGit = simpleGit(tempDir);
    await localGit.checkoutLocalBranch(branchName);

    const filePath = path.join(tempDir, result.patch_filename);
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, result.patch_content);

    await localGit.add(result.patch_filename);
    await localGit.commit(`Fix issue #${issueNumber}: ${result.summary}`);
    await localGit.push("origin", branchName);

    const prBody = `Automated PR generated by Claude to fix issue #${issueNumber}.\n\n### Analysis:\n${result.summary}`;
    const pr = await createGiteaPR(owner, repo, "main", branchName, `Fix #${issueNumber}: ${issue.title}`, prBody);
    
    await updateGiteaIssue(owner, repo, issueNumber, `🚀 **Auto-fix PR created:** ${pr.html_url}`);
    await sendSlackAlert(`✅ Auto-fix PR generated for Issue #${issueNumber}`);

  } catch (error) {
    console.error("Error during auto-fix:", error);
  } finally {
    // Cleanup tempDir in a real scenario
  }
}

const PORT = process.env.PORT || 8080;
app.listen(PORT, () => console.log(`Webhook server running on port ${PORT}`));
